;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        iy-go-to-char--command
        jump-char-process-char
        kill-region
        picture-backward-clear-column
        picture-backward-column
        picture-move-down
        puppet-interpolate
        py-electric-comment
        py-newline-and-indent
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        ido-switch-buffer
        isearch-abort
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-other-meta-char
        isearch-printing-char
        picture-move-up
        yank-rectangle
        ))
