;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        iy-go-to-char--command
        jump-char-process-char
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        isearch-abort
        isearch-forward-regexp
        isearch-other-meta-char
        isearch-other-meta-char
        isearch-printing-char
        yank-rectangle
        ))
