(diminish 'mouse-wheel-mode)
(diminish 'global-whitespace-mode)
(diminish 'magit-auto-revert-mode)
(diminish 'flyspell-mode)
(diminish 'highlight-symbol-mode)
(diminish 'yas-minor-mode)
(diminish 'auto-complete-mode)
